---
collections:
- ansible.posix
- name: community.general
  version: 5.2.0
- name: leonardehrenfried.baseline
  version: 0.1.0
- name: devsec.hardening
  version: 7.15.0

roles:
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0
