---
collections:
- ansible.posix
- name: community.general
  version: 3.7.0
- name: leonardehrenfried.baseline
  version: 0.1.0

roles:
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0
- src: dev-sec.ssh-hardening
  version: 9.7.0
